### ISSUE TITLE
Can't spawn actors in Rubinius

### ISSUE THREAD

**Issue by asppsa** [ruby-concurrency/concurrent-ruby#367]
Hi there,

Since 0.9 (edge 0.1), it seems that actors in Rubinius are broken.  Judging from the backtrace, the issue is somewhere in the new futures implementation:

~~~
irb(main):001:0> require 'concurrent'
=> true
irb(main):002:0> require 'concurrent-edge'
=> true
irb(main):004:0> Class.new(Concurrent::Actor::Context).spawn('test')
NoMethodError: undefined method `peek' on an instance of Array.
	from kernel/delta/kernel.rb:78:in `peek (method_missing)'
	from /home/asp/.gem/rbx/2.1.0/gems/concurrent-ruby-edge-0.1.0/lib/concurrent/edge/future.rb:375:in `wait_until_complete'
	from /home/asp/.gem/rbx/2.1.0/gems/concurrent-ruby-edge-0.1.0/lib/concurrent/edge/future.rb:761:in `wait_until_complete!'
	from /home/asp/.gem/rbx/2.1.0/gems/concurrent-ruby-edge-0.1.0/lib/concurrent/edge/future.rb:597:in `value!'
	from /home/asp/.gem/rbx/2.1.0/gems/concurrent-ruby-edge-0.1.0/lib/concurrent/actor.rb:45:in `root'
	from /home/asp/.gem/rbx/2.1.0/gems/concurrent-ruby-edge-0.1.0/lib/concurrent/actor.rb:71:in `spawn'
	from /home/asp/.gem/rbx/2.1.0/gems/concurrent-ruby-edge-0.1.0/lib/concurrent/actor/context.rb:117:in `spawn'
	from (irb):4
	from kernel/common/block_environment.rb:53:in `call_on_instance'
	from kernel/common/eval.rb:176:in `eval'
	from kernel/common/kernel.rb:511:in `loop'
	from kernel/bootstrap/proc.rb:20:in `call'
	from kernel/common/throw_catch.rb:30:in `catch'
	from kernel/common/throw_catch.rb:8:in `register'
	from kernel/common/throw_catch.rb:29:in `catch'
	from kernel/bootstrap/proc.rb:20:in `call'
	from kernel/common/throw_catch.rb:30:in `catch'
	from kernel/common/throw_catch.rb:8:in `register'
	from kernel/common/throw_catch.rb:29:in `catch'
	from /home/asp/.rvm/rubies/rbx-2.5.7/gems/gems/rubysl-irb-2.1.1/bin/irb:12:in `__script__'
	from kernel/common/kernel.rb:498:in `load'
	from /home/asp/.rvm/rubies/rbx-2.5.7/gems/bin/irb:23:in `__script__'
	from kernel/common/block_environment.rb:53:in `call_on_instance'
	from kernel/common/eval.rb:176:in `eval'
	from /home/asp/.gem/rbx/2.1.0/bin/ruby_executable_hooks:15:in `__script__'
	from kernel/delta/code_loader.rb:66:in `load_script'
	from kernel/delta/code_loader.rb:152:in `load_script'
	from kernel/loader.rb:656:in `script'
	from kernel/loader.rb:842:in `main'
irb(main):006:0> RUBY_ENGINE
=> "rbx"
irb(main):007:0> RUBY_ENGINE_VERSION
=> "2.5.7"
~~~

**Comment by asppsa** [comment]
So there is an instance variable clash -- `@Waiters` is defined in `lib/concurrent/synchronization/rbx_object.rb` as an array.

**Comment by pitr-ch** [comment]
Thanks you very much for reporting and finding the bug.

**Comment by jdantonio** [comment]
@asppsa @pitr-ch Can we close this issue, or are we waiting for more testing?

**Comment by asppsa** [comment]
Yep, I am happy to close if @pitr-ch is.
