### ISSUE TITLE
Inconsistent `flat` behavior

### ISSUE THREAD

**Issue by hobodave** [ruby-concurrency/concurrent-ruby#426]
Using concurrent-ruby-edge 0.2.0pre2 on jRuby 9.0.1.0.

The FlatPromise only resolves if the contained future is successful. If the inner future fails, or raises, then the flat never resolves and hangs the program if you `wait` or call `value`.

```ruby
# Works
foo = Concurrent.future { Concurrent.future { 7 } }.flat
foo.value! # 7

# Fails
bar = Concurrent.future { Concurrent.future { raise "no" } }.flat
bar.value! # Hangs

# OR

baz = Concurrent.future { Concurrent.failed_future("no") }.flat
baz.value! # Hangs
```

**Comment by hobodave** [comment]
FYI, using jRuby 9.0.1.0. 

Also, we noticed that this behavior differed sometimes during repeated executions:

```ruby
# Often 
foo = Concurrent.future { Concurrent.failed_future(StandardError.new('fail')) }.flat # Returns Future
foo.value # Hangs

# Sometimes
foo = Concurrent.future { Concurrent.failed_future(StandardError.new('fail')) }.flat  # Raises following Exception

=begin
StandardError: fail
	from /Users/davida/.rvm/gems/jruby-9.0.1.0@deal-management-api/gems/concurrent-ruby-edge-0.2.0.pre2/lib/concurrent/edge/future.rb:765:in `wait_until_complete!'
	from /Users/davida/.rvm/gems/jruby-9.0.1.0@deal-management-api/gems/concurrent-ruby-edge-0.2.0.pre2/lib/concurrent/edge/future.rb:600:in `value!'
	from /Users/davida/.rvm/gems/jruby-9.0.1.0@deal-management-api/gems/concurrent-ruby-edge-0.2.0.pre2/lib/concurrent/edge/future.rb:1144:in `process_on_done'
	from /Users/davida/.rvm/gems/jruby-9.0.1.0@deal-management-api/gems/concurrent-ruby-edge-0.2.0.pre2/lib/concurrent/edge/future.rb:995:in `on_done'
	from /Users/davida/.rvm/gems/jruby-9.0.1.0@deal-management-api/gems/concurrent-ruby-edge-0.2.0.pre2/lib/concurrent/edge/future.rb:403:in `pr_callback_notify_blocked'
	from /Users/davida/.rvm/gems/jruby-9.0.1.0@deal-management-api/gems/concurrent-ruby-edge-0.2.0.pre2/lib/concurrent/edge/future.rb:806:in `pr_callback_notify_blocked'
	from /Users/davida/.rvm/gems/jruby-9.0.1.0@deal-management-api/gems/concurrent-ruby-edge-0.2.0.pre2/lib/concurrent/edge/future.rb:778:in `call_callback'
	from /Users/davida/.rvm/gems/jruby-9.0.1.0@deal-management-api/gems/concurrent-ruby-edge-0.2.0.pre2/lib/concurrent/edge/future.rb:746:in `add_callback'
	from /Users/davida/.rvm/gems/jruby-9.0.1.0@deal-management-api/gems/concurrent-ruby-edge-0.2.0.pre2/lib/concurrent/edge/future.rb:1150:in `process_on_done'
	from /Users/davida/.rvm/gems/jruby-9.0.1.0@deal-management-api/gems/concurrent-ruby-edge-0.2.0.pre2/lib/concurrent/edge/future.rb:995:in `on_done'
	from /Users/davida/.rvm/gems/jruby-9.0.1.0@deal-management-api/gems/concurrent-ruby-edge-0.2.0.pre2/lib/concurrent/edge/future.rb:403:in `pr_callback_notify_blocked'
	from /Users/davida/.rvm/gems/jruby-9.0.1.0@deal-management-api/gems/concurrent-ruby-edge-0.2.0.pre2/lib/concurrent/edge/future.rb:806:in `pr_callback_notify_blocked'
	from /Users/davida/.rvm/gems/jruby-9.0.1.0@deal-management-api/gems/concurrent-ruby-edge-0.2.0.pre2/lib/concurrent/edge/future.rb:778:in `call_callback'
	from /Users/davida/.rvm/gems/jruby-9.0.1.0@deal-management-api/gems/concurrent-ruby-edge-0.2.0.pre2/lib/concurrent/edge/future.rb:746:in `add_callback'
	from /Users/davida/.rvm/gems/jruby-9.0.1.0@deal-management-api/gems/concurrent-ruby-edge-0.2.0.pre2/lib/concurrent/edge/future.rb:989:in `block in initialize'
	from /Users/davida/.rvm/gems/jruby-9.0.1.0@deal-management-api/gems/concurrent-ruby-edge-0.2.0.pre2/lib/concurrent/edge/lock_free_stack.rb:80:in `each'
	from /Users/davida/.rvm/gems/jruby-9.0.1.0@deal-management-api/gems/concurrent-ruby-edge-0.2.0.pre2/lib/concurrent/edge/future.rb:989:in `initialize'
	from /Users/davida/.rvm/gems/jruby-9.0.1.0@deal-management-api/gems/concurrent-ruby-edge-0.2.0.pre2/lib/concurrent/edge/future.rb:1163:in `initialize'
	from /Users/davida/.rvm/gems/jruby-9.0.1.0@deal-management-api/gems/concurrent-ruby-1.0.0.pre2-java/lib/concurrent/synchronization/object.rb:73:in `new'
	from /Users/davida/.rvm/gems/jruby-9.0.1.0@deal-management-api/gems/concurrent-ruby-edge-0.2.0.pre2/lib/concurrent/edge/future.rb:644:in `flat'
	from (irb):63:in `<eval>'
=end
```

**Comment by pitr-ch** [comment]
Thank you for letting us know, I'll investigate.

**Comment by pitr-ch** [comment]
Please try #428, I've just noticed your PR, Thanks, I'll try that too.
