### ISSUE TITLE
test failure for 'Concurrent::Channel goroutines .go_loop loops until the block returns false'

### ISSUE THREAD

**Issue by wwood** [ruby-concurrency/concurrent-ruby#534]
Hi,

I'm trying to run the tests but I'm running into this error:
```
Failures:

  1) Concurrent::Channel goroutines .go_loop loops until the block returns false
     Failure/Error: Channel.go_loop do
     Concurrent::RejectedExecutionError:
       Concurrent::RejectedExecutionError
     # ./lib/concurrent/executor/abstract_executor_service.rb:76:in `handle_fallback'
     # ./lib/concurrent/executor/ruby_executor_service.rb:21:in `block in post'
     # ./lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'
     # ./lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
     # ./lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
     # ./lib/concurrent/executor/ruby_executor_service.rb:19:in `post'
     # ./lib/concurrent/channel.rb:238:in `go_loop_via'
     # ./lib/concurrent/channel.rb:233:in `go_loop'
     # ./spec/concurrent/channel_spec.rb:605:in `block (4 levels) in <module:Concurrent>'

Finished in 2 minutes 42.3 seconds (files took 0.52025 seconds to load)
2434 examples, 1 failure, 7 pending

Failed examples:

rspec ./spec/concurrent/channel_spec.rb:601 # Concurrent::Channel goroutines .go_loop loops until the block returns false

Randomized with seed 32790

/gnu/store/z7393wcsqgrvbh5ywkjrfc9n6fqyn560-ruby-2.3.1/bin/ruby -I/gnu/store/iz4fzkr8mlfiq2dfgi81sx7mnbwvw6ja-profile/lib/ruby/gems/2.3.0/gems/rspec-support-3.2.2/lib:/gnu/store/iz4fzkr8mlfiq2dfgi81sx7mnbwvw6ja-profile/lib/ruby/gems/2.3.0/gems/rspec-core-3.2.3/lib /gnu/store/iz4fzkr8mlfiq2dfgi81sx7mnbwvw6ja-profile/lib/ruby/gems/2.3.0/gems/rspec-core-3.2.3/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```
Is this a known test failure? Is it reproducible by others? Thanks. i'm using the newest master i.e. 0d044bebdda2781b1b265472555090941232bbe5

Thanks,
ben

**Comment by jdantonio** [comment]
This test fails regularly, probably because of a bug. Our channel implementation is highly experimental. It's in our Edge gem (not core) and it is _not_ suitable for production use.

**Comment by wwood** [comment]
OK, thanks, I figured as much after submitting this report. I've pushed ruby-concurrency disabling this test to the Guix repo.
