### ISSUE TITLE
undefined method 'schedule_time' using ScheduledTask.execute

### ISSUE THREAD

**Issue by ryansch** [ruby-concurrency/concurrent-ruby#548]
I'm trying to reschedule an actor with the following code:
```ruby
require 'concurrent'
require 'concurrent-edge'
require 'consul_bridge/bootstrap_consul'

module ConsulBridge
  class BootstrapConsulActor < Concurrent::Actor::RestartingContext
    def initialize(bucket:, join_all: false)
      @bucket = bucket
      @join_all = join_all
    end

    def on_message(message)
      if message == :bootstrap
        begin
          BootstrapConsul.call(bucket: @bucket, join_all: @join_all)
        rescue => e
          puts "Warning: #{e.message}; retrying in 5 seconds"
          Concurrent::ScheduledTask.execute(5){ tell :bootstrap }
        end
      else
        pass
      end
    end
  end
end
```

This causes the following log output:
```
Warning: Unable to join at least 2 masters with join_all; retrying in 5 seconds
[2016-07-04 16:16:50.808] ERROR -- /bootstrap_consul: undefined method `schedule_time' for #<Object:0x00562c8a3b4360> (NoMethodError)
/usr/local/bundle/gems/concurrent-ruby-1.0.2/lib/concurrent/scheduled_task.rb:201:in `<=>'
/usr/local/bundle/gems/concurrent-ruby-edge-0.2.2/lib/concurrent/actor/behaviour/sets_results.rb:15:in `=='
/usr/local/bundle/gems/concurrent-ruby-edge-0.2.2/lib/concurrent/actor/behaviour/sets_results.rb:15:in `!='
/usr/local/bundle/gems/concurrent-ruby-edge-0.2.2/lib/concurrent/actor/behaviour/sets_results.rb:15:in `on_envelope'
/usr/local/bundle/gems/concurrent-ruby-edge-0.2.2/lib/concurrent/actor/core.rb:161:in `process_envelope'
/usr/local/bundle/gems/concurrent-ruby-edge-0.2.2/lib/concurrent/actor/core.rb:95:in `block in on_envelope'
/usr/local/bundle/gems/concurrent-ruby-edge-0.2.2/lib/concurrent/actor/core.rb:118:in `block (2 levels) in schedule_execution'
/usr/local/bundle/gems/concurrent-ruby-1.0.2/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'
/usr/local/bundle/gems/concurrent-ruby-1.0.2/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
/usr/local/bundle/gems/concurrent-ruby-1.0.2/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
/usr/local/bundle/gems/concurrent-ruby-edge-0.2.2/lib/concurrent/actor/core.rb:115:in `block in schedule_execution'
/usr/local/bundle/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/serialized_execution.rb:18:in `call'
/usr/local/bundle/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/serialized_execution.rb:96:in `work'
/usr/local/bundle/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/serialized_execution.rb:77:in `block in call_job'
/usr/local/bundle/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/usr/local/bundle/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/usr/local/bundle/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/usr/local/bundle/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/usr/local/bundle/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/usr/local/bundle/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

It does however reschedule the actor and execution continues.  I'm using ruby 2.3.1p112.  Complete source code: https://github.com/outstand/consul_bridge

**Comment by ryansch** [comment]
I figured this out.  I wasn't using the return value from `on_message` so I wasn't paying attention to what it was.  Explicitly returning `nil` causes this error to go away.
