### ISSUE TITLE
Two tests fail on Alpine Linux armhf, running with -ext

### ISSUE THREAD

**Issue by jirutka** [ruby-concurrency/concurrent-ruby#689]
I’m getting the following failures on Alpine Linux armhf. All tests pass on other architectures, so the problem is related to armhf platform.

```
Failures:

  1) Concurrent::Map #inspect
     Failure/Error: expect(Concurrent::Map.new.inspect).to match(regexp)

       expected "#<Concurrent::Map:0x-537308c8 entries=0 default_proc=nil>" to match /\A#<Concurrent::Map:0x[0-9a-f]+ entries=[0-9]+ default_proc=.*>\Z/i
       Diff:
       @@ -1,2 +1,2 @@
       -/\A#<Concurrent::Map:0x[0-9a-f]+ entries=[0-9]+ default_proc=.*>\Z/i
       +"#<Concurrent::Map:0x-537308c8 entries=0 default_proc=nil>"
     # ./spec/concurrent/map_spec.rb:798:in `block (2 levels) in <module:Concurrent>'

  2) Concurrent::Promises Future constructs promise like tree
     Failure/Error: expect(head.to_s).to match /<#Concurrent::Promises::Future:0x[\da-f]+ pending>/

       expected "<#Concurrent::Promises::Future:0x..facab5450 pending>" to match /<#Concurrent::Promises::Future:0x[\da-f]+ pending>/
       Diff:
       @@ -1,2 +1,2 @@
       -/<#Concurrent::Promises::Future:0x[\da-f]+ pending>/
       +"<#Concurrent::Promises::Future:0x..facab5450 pending>"
     # ./spec/concurrent/edge/promises_spec.rb:374:in `block (3 levels) in <top (required)>'

Finished in 2 minutes 22.9 seconds (files took 3.8 seconds to load)
2047 examples, 2 failures, 7 pending
```

* * *
-   Operating system: linux
-   `concurrent-ruby` version: 1.0.5
-   `concurrent-ruby-ext` installed: yes
-   `concurrent-ruby-edge` used: no

**Comment by pitr-ch** [comment]
Hi, thanks for reporting! https://github.com/ruby-concurrency/concurrent-ruby/pull/651 partially fixes it. I am looking at the rest.

**Comment by pitr-ch** [comment]
https://github.com/ruby-concurrency/concurrent-ruby/pull/699 should fix the rest, @jirutka could you verify?

**Comment by pitr-ch** [comment]
Both fixes are merged, @jirutka I'll keep this open, could you test master that it passes?
