### ISSUE TITLE
[JRuby, Java-10] Error: illegal access on 'submit'

### ISSUE THREAD

**Issue by prashantvithani** [ruby-concurrency/concurrent-ruby#758]
Getting this error while using `TimerTask`

```
TypeError:
  illegal access on 'submit': class org.jruby.javasupport.JavaMethod cannot access a member of class java.util.concurrent.Executors$DelegatedExecutorService (in module java.base) with modifiers "public"
# /Users/prvithani/Workspace/concurrent-ruby/lib/concurrent/executor/java_executor_service.rb:30:in `post'
# /Users/prvithani/Workspace/concurrent-ruby/lib/concurrent/executor/timer_set.rb:105:in `ns_post_task'
# /Users/prvithani/Workspace/concurrent-ruby/lib/concurrent/executor/timer_set.rb:93:in `block in post_task'
# com/concurrent_ruby/ext/SynchronizationLibrary.java:231:in `synchronize'
# /Users/prvithani/Workspace/concurrent-ruby/lib/concurrent/executor/timer_set.rb:93:in `post_task'
# /Users/prvithani/Workspace/concurrent-ruby/lib/concurrent/scheduled_task.rb:302:in `ns_schedule'
# /Users/prvithani/Workspace/concurrent-ruby/lib/concurrent/scheduled_task.rb:262:in `block in execute'
# com/concurrent_ruby/ext/SynchronizationLibrary.java:231:in `synchronize'
# /Users/prvithani/Workspace/concurrent-ruby/lib/concurrent/scheduled_task.rb:262:in `execute'
# /Users/prvithani/Workspace/concurrent-ruby/lib/concurrent/scheduled_task.rb:278:in `execute'
# /Users/prvithani/Workspace/concurrent-ruby/lib/concurrent/timer_task.rb:304:in `schedule_next_task'
# /Users/prvithani/Workspace/concurrent-ruby/lib/concurrent/timer_task.rb:220:in `block in execute'
# com/concurrent_ruby/ext/SynchronizationLibrary.java:231:in `synchronize'
# /Users/prvithani/Workspace/concurrent-ruby/lib/concurrent/timer_task.rb:217:in `execute'
```

```
* Operating system:                mac
* Ruby implementation:             JRuby
* `concurrent-ruby` version:       1.0.5
* `concurrent-ruby-ext` installed: no
* `concurrent-ruby-edge` used:     yes
```
Java version
```
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
```

JRuby version
```
jruby 9.2.0.0 (2.5.0) 2018-05-24 81156a8 Java HotSpot(TM) 64-Bit Server VM 10.0.2+13 on 10.0.2+13 [darwin-x86_64]
```

**Comment by pitr-ch** [comment]
Thanks for reporting @prashantvithani! It might be a problem with java modules. I am marking with `looking-for-contributor` for now. Maybe somebody will donate some of theirs time to dig into it, before I'll be able to.

**Comment by prashantvithani** [comment]
I don't have much experience with JRuby as I've started exploring it just recently. I'll try to look into the functioning of Java modules and check whether it's just the issue with `TimerTask (SingleThreadExecutor)` or happening with others (`ThreadPoolExecutor`) as well.

**Comment by pitr-ch** [comment]
Thanks a lot!

**Comment by prashantvithani** [comment]
I've raised a PR. Removing `java_alias` and calling java method directly solves this issue. However, it works fine in JDK-8
