### ISSUE TITLE
illegal access on 'newThread': class org.jruby.javasupport.JavaMethod (in module org.jruby.dist) cannot access a member of class java.util.concurrent.Executors$DefaultThreadFactory (in module java.base) with modifiers "public"

### ISSUE THREAD

**Issue by goyachanpuru** [ruby-concurrency/concurrent-ruby#850]
```
* Operating system:                mac
* Ruby implementation:             JRuby 
* `concurrent-ruby` version:       9.2.9.0 (2.5.7)
* `ActiveJob`                      version 6.0.2.1
```

When useing ActiveJob with "config.queue_adapter = ActiveJob::QueueAdapters::AsyncAdapter.new" with concurrent-ruby 1.1.6, the error is occured.
But it works with concurrent-ruby 1.1.5.

The backtrace is as follows.

```
concurrent-ruby (1.1.6) lib/concurrent-ruby/concurrent/executor/java_executor_service.rb:94:in `newThread'
concurrent-ruby (1.1.6) lib/concurrent-ruby/concurrent/executor/java_executor_service.rb:24:in `post'
activejob (6.0.2.1) lib/active_job/queue_adapters/async_adapter.rb:93:in `enqueue'
activejob (6.0.2.1) lib/active_job/queue_adapters/async_adapter.rb:40:in `enqueue'
activejob (6.0.2.1) lib/active_job/enqueuing.rb:57:in `block in enqueue'
activesupport (6.0.2.1) lib/active_support/callbacks.rb:112:in `block in run_callbacks'
activesupport (6.0.2.1) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.2.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.2.1) lib/active_support/notifications.rb:180:in `instrument'
activejob (6.0.2.1) lib/active_job/logging.rb:35:in `block in Logging'
org/jruby/RubyBasicObject.java:2680:in `instance_exec'
activesupport (6.0.2.1) lib/active_support/callbacks.rb:121:in `block in run_callbacks'
activejob (6.0.2.1) lib/active_job/logging.rb:16:in `block in Logging'
activejob (6.0.2.1) lib/active_job/logging.rb:45:in `block in tag_logger'
activesupport (6.0.2.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.2.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.2.1) lib/active_support/tagged_logging.rb:80:in `tagged'
activejob (6.0.2.1) lib/active_job/logging.rb:45:in `tag_logger'
activejob (6.0.2.1) lib/active_job/logging.rb:15:in `block in Logging'
org/jruby/RubyBasicObject.java:2680:in `instance_exec'
activesupport (6.0.2.1) lib/active_support/callbacks.rb:121:in `block in run_callbacks'
activesupport (6.0.2.1) lib/active_support/callbacks.rb:139:in `run_callbacks'
activejob (6.0.2.1) lib/active_job/enqueuing.rb:53:in `enqueue'
activejob (6.0.2.1) lib/active_job/enqueuing.rb:22:in `perform_later'
```

**Comment by pitr-ch** [comment]
What Java version do you use? 
(Note: could it be related to issues https://github.com/ruby-concurrency/concurrent-ruby/pull/840 ?)

**Comment by headius** [comment]
I suspect this code uses `java_method` to access a specific method. That issue is fixed in jruby/jruby#5841.

**Comment by goyachanpuru** [comment]
@pitr-ch 
Java version I use is as below.

```
java -version                                                                                                                                                                                                                                                                                                                                                                                                                                                                [13:46:38]
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.15.1, JRE 11 Mac OS X amd64-64-Bit Compressed References 20190823_327 (JIT enabled, AOT enabled)
OpenJ9   - 0f66c6431
OMR      - ec782f26
JCL      - fa49279450 based on jdk-11.0.4+11)
```

**Comment by pitr-ch** [comment]
Thanks, @goyachanpuru could you try with JRuby 9.2.10.0 if it is fixed?

**Comment by olleolleolle** [comment]
Eh, JRuby 9.2.11.0 is now out, so try with that!

**Comment by goyachanpuru** [comment]
@pitr-ch @olleolleolle 
My Rails application has worked well using JRuby 9.2.11.0 (2.5.7). :tada:
Thank you for help so kindly. 


■ my jruby version:  jruby 9.2.11.0 (2.5.7) 2020-03-02 612d7a05a6 Eclipse OpenJ9 VM openj9-0.15.1 on 11.0.4+11 +jit [darwin-x86_64]

**Comment by pitr-ch** [comment]
@goyachanpuru great to hear that!
